//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // isim uzayýmýzý buraya yapýþtýrdýk-veri denetimleri için meta verileri tanýmlamak üzere kullanýlan öznitelik sýnýflarý saðlar.
    public partial class TBLmusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLmusteriler()
        {
            this.TBLsatis = new HashSet<TBLsatis>();
        }
    
        public int MUSTERIID { get; set; }
        [Required(ErrorMessage ="Bu Alaný Boþ Býrakamazssýnýz !!!")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik isim giriniz !")]
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLsatis> TBLsatis { get; set; }
    }
}
